import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })



import img_vercel from '@/assets/vercel.svg'
import img_next from '@/assets/next.svg'
import img_thirteen from '@/assets/thirteen.svg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src={img_vercel}
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src={img_next}
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src={img_thirteen}
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="about" className={styles.card}>
            <h2 className={inter.className}>
              About <span>-&gt;</span>
            </h2>
          </Link>
          <Link href="me" className={styles.card}>
            <h2 className={inter.className}>
              me <span>-&gt;</span>
            </h2>
          </Link>
          <Link href="/" className={styles.card}>
            <h2 className={inter.className}>
              home <span>-&gt;</span>
            </h2>
          </Link>
          

        </div>
      </main>
    </>
  )
}
